name: Publish Gem

on:
  push:
    tags:
      - 'v*.*.*'  # Runs only when a version tag (e.g., v1.2.3) is pushed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Clones submodules

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Node.js version

      - name: Install npm dependencies
        run: npm install

      - name: Build static assets
        run: npm run build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust to your gem's Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build *.gemspec

      - name: Publish gem to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push *.gem
